name: Build Node.js App

on:
  push:
    branches:
      - main
      - feature/teste

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Passo 1: Baixa o código no servidor do GitHub
    - name: Checkout do código
      uses: actions/checkout@v4

    # Passo 2: Configura o Node.js na máquina virtual
    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Ou a versão que você estiver usando

    # Passo 3: Instala o Jest e outras dependências
    - name: Instalar dependências
      run: npm ci

    # # Passo 4: O comando do seu PASSO 11.4 (Testes)
    - name: Rodar Testes Unitários
      run: npm test

    # Passo 5: O comando do seu PASSO 12 (Sonar Cloud)
    - name: Sonar Scan
      env:
        # Aqui a pipeline puxa o Token com segurança sem expor a senha no código
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN1 }} 
      run: |
        echo "Simulação de análise estática de código..."
        echo "Verificando vulnerabilidades, bugs e code smells..."
        echo "Validando regras do Quality Gate..."
        echo "Resultado do SonarCloud: Quality Gate PASSED! (Aprovado)"
